version: 0.2

phases:
  install:
    commands:
      - cd server  # Change directory to the server folder
      - npm install  # Install dependencies

artifacts:
  files:
    - '**/*'
  base-directory: 'server'  # Set this to where your main application files are located

cache:
  paths:
    - 'server/node_modules/**/*'  # Cache the node_modules directory to speed up builds
