version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
      - cd client && npm install
  pre_build:
    commands:
      - echo Build started on `date`
  build:
    commands:
      - echo Building the React App...
      - npm run build
artifacts:
  files:
    - '**/*'
  name:"movie-app"
  base-directory: 'client/build'
